### ISSUE TITLE
Docker container error on example.ipynb

### ISSUE THREAD

**Issue by robmarkcole** [OpenGeoscience/geonotebook#169]
Hi
running the Docker container and following [01_Example.ipynb](https://github.com/OpenGeoscience/geonotebook/blob/master/notebooks/01_Example.ipynb), I immediately hit the following error and the kernel dies:

```
[E 08:53:41.324 NotebookApp] 500 POST /api/kernels/4d3b35a2-ebc1-41a6-8e89-8f2aa40ef632/restart (172.17.0.1) 31048.51ms referer=http://localhost:8888/notebooks/Geonotebook/01_Example.ipynb
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 226, in dispatch_shell
    self.pre_handler_hook()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 241, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
```

**Comment by magamonsta** [comment]
I'm getting the same error.  
I built the container with 
docker build -t geonotebook .
and then once that completed with no errors i ran: docker run -p 8888:8888 -v /path/to/your/notebooks:/notebooks  -it --rm geonotebook

and i replaced /path/to/your/notebooks with the examples director included and i almost immediately get the same error as above

**Comment by magamonsta** [comment]
was able to "fix" the error by just pulling the image directly from docker hub

**Comment by syncharny** [comment]
I downloaded from docker hub and still got this error:

```
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 226, in dispatch_shell
    self.pre_handler_hook()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 241, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
ValueError: signal only works in main thread
```
