### ISSUE TITLE
add raster layer failed in Example02_raster_Data

### ISSUE THREAD

**Issue by shenweiqing** [OpenGeoscience/geonotebook#170]
Hi，I have a problem about adding and showing a raster on the map. I  would appreciate any help in debugging and tracking down the error source. 
I pull the lastest geonotebook image by run the code
``` pull geonotebook/geonotebook``` and use default config
When I run ``` M.add_layer(rd, opacity=1.0, gamma=2.5) ``` in  02_Raster_Data.ipynb,
nothing appears on the map. (I have tried chrome、Firefox and edge web browser)
But I think I read the raster image, because I can see the max and min values of the bands, besides ```M.layers``` is not an empty collection.
when I press F12 to see the chrome web browser console message.  There is a log reads
```
127.0.0.1:8888/ktile/69554045-2827-4058-8ec4-3cb375a2a9ee/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_16693297702632292612/19/42/7.png?:1 GET http://127.0.0.1:8888/ktile/69554045-2827-4058-8ec4-3cb375a2a9ee/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_16693297702632292612/19/42/7.png? net::ERR_CONNECTION_REFUSED
```
I enter the container and try to check if  there is a file names 7.png, but i find none.
``` docker exec -it containerid /bin/bash```
```find / -name 7.png``` 
Please let me know what additional info would be helpful in debugging this.
Thanks!

**Comment by shenweiqing** [comment]
when i use ``` docker log container_id``` to see the logs
there is a error log reads
```
[E 05:19:37.334 NotebookApp] Uncaught exception GET /ktile/4a269569-eaf7-4998-9111-ed8121e2b13c/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_267297346665224784/20/45/7.png?:1 (37.204.201.64)
    HTTPServerRequest(protocol='http', host='114.116.17.194:8999', method='GET', uri='/ktile/4a269569-eaf7-4998-9111-ed8121e2b13c/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_267297346665224784/20/45/7.png?:1', version='HTTP/1.1', remote_ip='37.204.201.64', headers={'Accept-Language': 'ru-RU', 'Accept-Encoding': 'gzip, deflate', 'Host': '114.116.17.194:8999', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; Touch; MAARJS)', 'Connection': 'Keep-Alive', 'Referer': 'https://yandex.ru/clck/jsredir?from=yandex.ru%3Bsearch%3Bweb%3B%3B&text=&etext=2032.uiloy6T9emHvK7C-bRoc9SiHssiXvGXbsrY4Hsfp7NBxsRSzoIYvW5bbxlWkbj11.16f3f2ac884f58cc641bd8b34fe8fc42a960df60&uuid=&state=_BLhILn4SxNIvvL0W45KSic66uCIg23qh8iRG98qeIXmeppkgUc0YLeQVNu7TCjFWhspMNrg36Y&data=UlNrNmk5WktYejR0eWJFYk1Ldmtxc3czSVk4eU8xbTNuNkFLT0I4TU9TdFNCNERibm5ibXhxQlZSNjZNRDdTRXgtWjBTQkMxcHlwc1lKcHZCRFJBRTFBMlNqODh1eUZNYU83MUVKZTBmM0hKTUlyb2lsUkhCLWRPc0dpc0xQQ21Ia3VsUGY5V3hCWUt6M2IzNmdWS2YycjgyaHIwX0JpUTRVbWViUjlseGJNa2M3YV8wNXNYdi1ONEtibmlEWnUzbG1vRC1lQkhQQ1dJMUhXZVc2Y3pKcENTRGxKZTVUUVgyckJQZUlocnRUZ0hna2tuRDdEVklKNEJuZFNqdWR2QXE3cklpa1FXNEhlalhZME1KdVN6WklsYjhOal9aZ3hVZmtBRlhPXzZYU1JZN1hQcTRfdE90Zw&b64e=2&sign=18e8f86b1e2aae44211d5e0cae92f176&keyno=0&cst=AiuY0DBWFJ7IXge4WdYJQa9gkHE_3kbi0nzC8WuQxITiUmNYi_WaZXK25ZfgOp0CKlPMnjyLrtDv3zzYI2hjYxzfipie_cxHx3LDtJwOtrmMWbYl7KO3eiYDUs08RYEkac-_dSjojGcUvemWXKYtEV_cZv9eqKt5&ref=orjY4mGPRjk5boDnW0uvlrrd71vZw9kp5uQozpMtKCXmyCrj7VrKuKcie1aBko0c6FPgiAUdSSjIJdg9ok-jqlmQFBhe3Mk9myuT-VseEp2nHU1gdzKHLf4WMAWVN7hi&l10n=ru&cts=1547355716387&mc=1.55224769864', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/geonotebook/vis/ktile/handler.py", line 143, in get
        config = self.ktile_config_manager[kernel_id]
      File "/usr/local/lib/python2.7/dist-packages/geonotebook/vis/ktile/ktile.py", line 30, in __getitem__
        return self._configs.__getitem__(*args, **kwargs)
    KeyError: u'4a269569-eaf7-4998-9111-ed8121e2b13c'
[E 05:19:37.369 NotebookApp] {
      "Accept-Language": "ru-RU", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "114.116.17.194:8999", 
      "Accept": "*/*", 
      "User-Agent": "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; Touch; MAARJS)", 
      "Connection": "Keep-Alive", 
      "Referer": "https://yandex.ru/clck/jsredir?from=yandex.ru%3Bsearch%3Bweb%3B%3B&text=&etext=2032.uiloy6T9emHvK7C-bRoc9SiHssiXvGXbsrY4Hsfp7NBxsRSzoIYvW5bbxlWkbj11.16f3f2ac884f58cc641bd8b34fe8fc42a960df60&uuid=&state=_BLhILn4SxNIvvL0W45KSic66uCIg23qh8iRG98qeIXmeppkgUc0YLeQVNu7TCjFWhspMNrg36Y&data=UlNrNmk5WktYejR0eWJFYk1Ldmtxc3czSVk4eU8xbTNuNkFLT0I4TU9TdFNCNERibm5ibXhxQlZSNjZNRDdTRXgtWjBTQkMxcHlwc1lKcHZCRFJBRTFBMlNqODh1eUZNYU83MUVKZTBmM0hKTUlyb2lsUkhCLWRPc0dpc0xQQ21Ia3VsUGY5V3hCWUt6M2IzNmdWS2YycjgyaHIwX0JpUTRVbWViUjlseGJNa2M3YV8wNXNYdi1ONEtibmlEWnUzbG1vRC1lQkhQQ1dJMUhXZVc2Y3pKcENTRGxKZTVUUVgyckJQZUlocnRUZ0hna2tuRDdEVklKNEJuZFNqdWR2QXE3cklpa1FXNEhlalhZME1KdVN6WklsYjhOal9aZ3hVZmtBRlhPXzZYU1JZN1hQcTRfdE90Zw&b64e=2&sign=18e8f86b1e2aae44211d5e0cae92f176&keyno=0&cst=AiuY0DBWFJ7IXge4WdYJQa9gkHE_3kbi0nzC8WuQxITiUmNYi_WaZXK25ZfgOp0CKlPMnjyLrtDv3zzYI2hjYxzfipie_cxHx3LDtJwOtrmMWbYl7KO3eiYDUs08RYEkac-_dSjojGcUvemWXKYtEV_cZv9eqKt5&ref=orjY4mGPRjk5boDnW0uvlrrd71vZw9kp5uQozpMtKCXmyCrj7VrKuKcie1aBko0c6FPgiAUdSSjIJdg9ok-jqlmQFBhe3Mk9myuT-VseEp2nHU1gdzKHLf4WMAWVN7hi&l10n=ru&cts=1547355716387&mc=1.55224769864", 
      "Cache-Control": "no-cache"
    }
[E 05:19:37.370 NotebookApp] 500 GET /ktile/4a269569-eaf7-4998-9111-ed8121e2b13c/L57.Globe.month09.2010.hh09vv04.h6v1.doy247to273.NBAR.v3.0_267297346665224784/20/45/7.png?:1 (37.204.201.64) 59.32ms referer=https://yandex.ru/clck/jsredir?from=yandex.ru%3Bsearch%3Bweb%3B%3B&text=&etext=2032.uiloy6T9emHvK7C-bRoc9SiHssiXvGXbsrY4Hsfp7NBxsRSzoIYvW5bbxlWkbj11.16f3f2ac884f58cc641bd8b34fe8fc42a960df60&uuid=&state=_BLhILn4SxNIvvL0W45KSic66uCIg23qh8iRG98qeIXmeppkgUc0YLeQVNu7TCjFWhspMNrg36Y&data=UlNrNmk5WktYejR0eWJFYk1Ldmtxc3czSVk4eU8xbTNuNkFLT0I4TU9TdFNCNERibm5ibXhxQlZSNjZNRDdTRXgtWjBTQkMxcHlwc1lKcHZCRFJBRTFBMlNqODh1eUZNYU83MUVKZTBmM0hKTUlyb2lsUkhCLWRPc0dpc0xQQ21Ia3VsUGY5V3hCWUt6M2IzNmdWS2YycjgyaHIwX0JpUTRVbWViUjlseGJNa2M3YV8wNXNYdi1ONEtibmlEWnUzbG1vRC1lQkhQQ1dJMUhXZVc2Y3pKcENTRGxKZTVUUVgyckJQZUlocnRUZ0hna2tuRDdEVklKNEJuZFNqdWR2QXE3cklpa1FXNEhlalhZME1KdVN6WklsYjhOal9aZ3hVZmtBRlhPXzZYU1JZN1hQcTRfdE90Zw&b64e=2&sign=18e8f86b1e2aae44211d5e0cae92f176&keyno=0&cst=AiuY0DBWFJ7IXge4WdYJQa9gkHE_3kbi0nzC8WuQxITiUmNYi_WaZXK25ZfgOp0CKlPMnjyLrtDv3zzYI2hjYxzfipie_cxHx3LDtJwOtrmMWbYl7KO3eiYDUs08RYEkac-_dSjojGcUvemWXKYtEV_cZv9eqKt5&ref=orjY4mGPRjk5boDnW0uvlrrd71vZw9kp5uQozpMtKCXmyCrj7VrKuKcie1aBko0c6FPgiAUdSSjIJdg9ok-jqlmQFBhe3Mk9myuT-VseEp2nHU1gdzKHLf4WMAWVN7hi&l10n=ru&cts=1547355716387&mc=1.55224769864
```
I would appreciate it if there is any help
